### ISSUE TITLE
How to open ContextMenuButton with single tap

### ISSUE THREAD

**Issue by FrankFundel** [dominicstop/react-native-ios-context-menu#10]
Yeah how to open the ContextMenu without holding the Button? :)

**Comment by guytepper** [comment]
You need to set `isMenuPrimaryAction` to `true` (Check out [`ContextMenuButton` props](https://github.com/dominicstop/react-native-ios-context-menu#312-contextmenubutton-component))

**Comment by und3f1n3d** [comment]
That's true for iOS 14. 

However,

> Note that ContextMenuButton is only available on iOS 14 and above. On iOS 13, it will use a ContextMenuButton, and on iOS 12 and below, it will use the ActionSheetFallback module to present a ActionSheetIOS menu.

With that, on iOS 13, you have to long press to show the menu.   My design team wished instead of a long press, a single tap should also trigger the action sheet. So i used [ActionSheetFallback Module](https://github.com/dominicstop/react-native-ios-context-menu#312-actionsheetfallback-module) as provided,


`   const actionSheetMenu = async () => await ActionSheetFallback.show(pullDownMenuConfig);    

return (<TouchableOpacity onPress={() => actionSheetMenu()}>
   <Text>ActionSheet Fallback with a tap</Text>
  </TouchableOpacity>);
`

so far it is working.. 🤞🏻 without any problems nor warnings 🤞🏻 .   hope this helps! 

⭐  Great work @dominicstop on the library and documentations. ⭐   I really like this library and the way how it is implemented.   I don't have to have spent hours to figure how to make this accessible! awesome!

**Comment by nandorojo** [comment]
You can use the `ContextMenuView`.
