### ISSUE TITLE
Initializer for conditional binding must have Optional type, not 'RCTMenuIcon'

### ISSUE THREAD

**Issue by raphaelrk** [dominicstop/react-native-ios-context-menu#4]
In RCTMenuActionItem.swift and RCTMenuItem.swift, getting the error "Initializer for conditional binding must have Optional type, not 'RCTMenuIcon'" when compiling. I wasn't getting this the other day so it may be related to the most recent XCode version, which I just updated to. Screenshots below:

![image](https://user-images.githubusercontent.com/3377845/99199333-5cb13280-276c-11eb-84d9-743fb586612e.png)

![image](https://user-images.githubusercontent.com/3377845/99199336-60dd5000-276c-11eb-9dda-491b4416fd12.png)

Not sure if this is correct, but it compiles when I change both to

```swift
    if let dict = dictionary["icon"] as? NSDictionary {
      self.icon = RCTMenuIcon(dictionary: dict);
    }
```

![image](https://user-images.githubusercontent.com/3377845/99199498-8e76c900-276d-11eb-9a17-0169780f648d.png)

**Comment by dominicstop** [comment]
Hello, sorry for the late reply (and thank you so much for the detailed explanation!)

I've doubled checked, and I'm not sure why Xcode is compiling when the code is clearly wrong?

![image](https://user-images.githubusercontent.com/18517029/99299580-5c0cbf00-2886-11eb-906c-aeeb134b783f.png)

I even deleted `derivedData` and did a clean build and it still compiles without any errors? Which is weird because `RCTMenuIcon(dictionary:)` is not a failable init., and it shouldn't be returning nil, so `if let` wouldn't be possible.

![image](https://user-images.githubusercontent.com/18517029/99299687-865e7c80-2886-11eb-9521-cb07c83cf9d1.png)

Thank you so much for catching this, I wouldn't have known otherwise 😭 (I'll release a patch with your changes as soon as possible...)

**Comment by dominicstop** [comment]
@raphaelrk hello, I've uploaded a [patch](https://github.com/dominicstop/react-native-ios-context-menu/releases/tag/v1.1.4) with your changes 😊 (please let me know if you find any other problems haha)
