### ISSUE TITLE
Add loading state

### ISSUE THREAD

**Issue by nandorojo** [dominicstop/react-native-ios-context-menu#44]
Could we add a `loading` state to menu items?

**Comment by dominicstop** [comment]
working on it it's just taking a bit longer since I had to refactor/rewrite a few things asadhsgjfhksldfsdlg

It's almost ready, just need to do a few more tests + write the examples haha

https://user-images.githubusercontent.com/18517029/175399937-e6f81ed8-02e6-4da6-87d4-43fe0abcfdcd.mov

(i'll close this issue once i release it in the next version ✨)

**Comment by dominicstop** [comment]
Hey, this has been added in version `1.10.0` so i'll be closing this issue now ✨
