### ISSUE TITLE
with AuxiliaryPreview, verylong text make the action not show full

### ISSUE THREAD

**Issue by fukemy** [dominicstop/react-native-ios-context-menu#50]
Hi, with verylong of text, the action does not display full, like below picture:
![Screen Shot 2022-08-08 at 17 30 17](https://user-images.githubusercontent.com/8202437/183398630-b6954d99-11cf-4c7b-afa2-6f4d72105060.png)

Can u take a look

**Comment by fukemy** [comment]
here is the video test with real device, for more information:
[video](https://streamable.com/yckndb)

**Comment by dominicstop** [comment]
Hi, unfortunately I do not have the time to tackle this issue at the moment, but there are workarounds you can employ in order to get around this bug ✨

### Workaround A: Negative Margins
If you know that the context menu preview will be very big, then assign a negative value `marginPreview` so that the aux. preview appears inside of the context menu preview.
```
auxiliaryPreviewConfig={{
  transitionEntranceDelay: 'RECOMMENDED',
  marginPreview: -100,
}}
```

![Simulator Screen Shot - iPhone 8 - 2022-08-11 at 18 27 25](https://user-images.githubusercontent.com/18517029/184114993-55dcf4fd-2daf-451c-9d01-71381ff2676c.png)

### Workaround B: Custom Preview
If you know that the context menu preview will be very big, then use a custom preview for it with a "truncated" version of the thing you want to show in the preview.

```
<ContextMenuView
  menuConfig={{
    menuTitle: 'ContextMenuAuxPreviewTest02',
  }}
  previewConfig={{
    previewType: isComponentBig ? 'CUSTOM' : 'DEFAULT'
  }}
  renderPreview={() => {
    return (
      <ComponentToShow shouldTruncate={true}/>
    );
  }}
>
  <ComponentToShow shouldTruncate={false}/>
</ContextMenuView>
```

hope this helps, xx

**Comment by fukemy** [comment]
nice solution, thank u
