### ISSUE TITLE
Option to present the context menu with my own target view?

### ISSUE THREAD

**Issue by oferRounds** [dominicstop/react-native-ios-context-menu#6]
Something similar to React Native’s Android function:
showPopupMenu(
        node: number,
        items: string[],
        error: () => void /* currently unused */,
        success: (item: string, index: number | undefined) => void,
    ): void;

where you just present it the context node, and presents it

**Comment by dominicstop** [comment]
Have you taken a look at [ContextMenuView Example #15](https://github.com/dominicstop/react-native-ios-context-menu#4115-contextmenuview-simple-example-15)? It lets you create a custom preview target (it's demoed in these gifs: [gif 1](https://github.com/dominicstop/react-native-ios-context-menu/blob/master/assets/context-menu-view-gifs/ContextMenuView-Test-07.gif), and [gif 2](https://github.com/dominicstop/react-native-ios-context-menu/blob/master/assets/context-menu-view-gifs/ContextMenuView-SimpleExample-15-16-17-18.gif))

![SimpleExample15](https://github.com/dominicstop/react-native-ios-context-menu/raw/master/assets/example-screenshots/ContextMenuView-SimpleExample15.png)

If you want to show a menu, maybe try checking out [ContextMenuButton Example #2](https://github.com/dominicstop/react-native-ios-context-menu#422-contextmenubutton-simple-example-2) (here's a [demo gif](https://github.com/dominicstop/react-native-ios-context-menu/blob/master/assets/context-menu-button-gifs/ContextMenuButton-SimpleExample-1-2.gif))

![SimpleExample02](https://github.com/dominicstop/react-native-ios-context-menu/raw/master/assets/example-screenshots/ContextMenuButton-SimpleExample02.png)


Though, unlike android, you can't show the menu programmatically (there's no api to do this, the user has to explicitly interact with it via a long press or a tap. I tried "faking" a press/long press via code, but the last time i tried, I couldn't get it to work.. 😭)

<br>

I kind of ran into the same problem, because sometimes you want to show a menu programmatically. I have been googling around, but iOS's `UIContextMenu` doesn't have an API to trigger the menu via code 😔

So i made a wrapper library around `UIPopoover` as a workaround called [react-native-ios-popover](https://github.com/dominicstop/react-native-ios-popover) so that I can show my own "menu" programmatically.

![popoverView-Example-1-2-3-4](https://raw.githubusercontent.com/dominicstop/react-native-ios-popover/master/assets/popover-view-gifs/PopoverView-Example-1-2-3-4.gif)

<br>

There's also the built in [`ActionSheetIOS`](https://reactnative.dev/docs/actionsheetios) module that lets you show a menu of options (I use it as a fallback for this library, [demo gif](https://github.com/dominicstop/react-native-ios-context-menu/blob/master/assets/context-menu-view-gifs/ContextMenuView-ActionSheetFallback-Test-1-to-6.gif))


Maybe for your use case, it's better to just show your own custom modal with some options.

**Comment by oferRounds** [comment]
Sorry for my delay @dominicstop, thank you so much for detailed answer! I have looked – but I’ll have a look again

**Comment by dominicstop** [comment]
Hope you find what you're looking for, good luck! ✨

**Comment by oferRounds** [comment]
Thank you!!! :) :) :)

**Comment by fukemy** [comment]
hi @oferRounds , whichs lib u used for android? I finding it too
